# Generated by Django 4.1.4 on 2022-12-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(default=5, max_length=50),
            preserve_default=False,
        ),
    ]
