# Generated by Django 4.1.4 on 2022-12-25 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='name',
        ),
    ]
