# Generated by Django 4.1.4 on 2022-12-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name_of_chat_room',
            field=models.CharField(default='noName', max_length=50),
            preserve_default=False,
        ),
    ]
