# Generated by Django 4.1.4 on 2022-12-25 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chat', '0006_alter_message_sender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extension', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('chats', models.ManyToManyField(to='chat.chat')),
                ('contacts', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
