# Generated by Django 4.1.4 on 2022-12-25 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userextension_chats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextension',
            name='chats',
        ),
        migrations.RemoveField(
            model_name='userextension',
            name='contacts',
        ),
    ]
