# Generated by Django 4.1.4 on 2022-12-25 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_remove_userextension_chats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='contacts',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
